### PR TITLE
Adds temperature compensation

### PR DESCRIPTION
**Pull request by purepani**
Adds logic to enable temperature compensation
Since this feature pretty much requires access to the offset properties, they should be added as well.
I didn't have time today, but might add them tomorrow.

Fixes https://github.com/adafruit/Adafruit_CircuitPython_MLX90393/issues/36

### CODE REVIEW

**Comment by purepani** [comment]
Oh, it looks like i didn't lint it.
I will do that tomorrow as well since i don't have pylint installed at the moment

**Review by FoamyGuy — APPROVED** [review]
This looks good to me. I do not have the hardware to test with. 

I did have a look thru the datasheet and the implementation here seems consistent with it as far as I understand it.

Thanks for adding this functionality @purepani

**Comment by purepani** [comment]
Thanks!
This isn't super useful at the moment actually bc I didn't add an api for setting the parameters for this iirc.

**Comment by brian-eng** [comment]
@purepani Any plans on adding the offsets? Enabling temperature compensation without them returns bad values.

**Comment by purepani** [comment]
I'm currently extremely busy with like 500 other things, so if you want to take a shot at a PR, go for it.
All it would require is reading and writing to a register. If it's something you really need and can't do it I can maybe write something quick, but no promises

**Pull request merged**
